# preload=/home/bugs/pix/wall/wallhaven-p8d6oj.jpg
# wallpaper=,/home/bugs/pix/wall/wallhaven-p8d6oj.jpg
preload = /home/sappy/Pictures/wallpapers/wallhaven-21krw9.jpg
wallpaper = , /home/sappy/Pictures/wallpapers/wallhaven-21krw9.jpg
splash=false
ipc=on
